#
# Test - run loops
#

"""Tests for the evidence loop.

The loop is a queue and a ``while True``, so what is worth testing is not that it iterates.
It is the four promises the rest of the architecture makes on its behalf: that a fold
produces exactly one evidence row and one state row, in that order; that shutdown loses
nothing; that a broken affect model stops the session rather than letting it run on with a
frozen face; and that stopping that way does not turn into a hang.

Written as plain synchronous tests wrapping a coroutine in ``asyncio.run``, rather than
taking a ``pytest-asyncio`` dependency. The wrapper is the whole of what that plugin would
remove, and dependencies here arrive when real code needs them.
"""

import asyncio
import contextlib
from datetime import datetime

import pytest

from asa.core.affect import (
    AffectEvidence,
    AffectState,
    AffectVector,
    Target,
)
from asa.core.loops import EvidenceLoop
from asa.core.observers import Event, Observers

NEUTRAL = AffectVector("basic4/1", {})


def _evidence(source: str = "test:producer") -> AffectEvidence:
    """One piece of evidence. ``source`` labels it so ordering can be asserted."""
    return AffectEvidence(
        target=Target.OTHER,
        affect=AffectVector("basic4/1", {"happiness": 0.8}),
        source=source,
    )


def _state(at: datetime) -> AffectState:
    """What a stand-in affect model hands back. Its contents are not the subject here."""
    return AffectState(other=NEUTRAL, self_=NEUTRAL, expressed=NEUTRAL, at=at)


async def _stop(task: "asyncio.Task[None]") -> None:
    """Cancel the consumer and wait for it, as the composition root will at shutdown.

    Awaiting the cancelled task matters: without it the event loop closes with the task
    still pending, and asyncio complains rather than the test saying anything useful.
    """
    task.cancel()
    with contextlib.suppress(asyncio.CancelledError):
        await task


def test_evidence_is_folded_and_both_records_are_published_in_order():
    """The contract in one test: one fold, one evidence row, one state row, in that order.

    Order is asserted rather than membership because the record is read as a sequence —
    the state a fold produced follows the evidence that produced it, and a reader pairing
    them relies on that. It also pins that the loop publishes *both*: the state row is the
    only place the model's belief is ever written down, since the model notifies nobody.
    """
    async def scenario() -> None:
        seen: list[Event] = []
        observers = Observers()
        observers.register(seen.append)

        folded: list[AffectEvidence] = []

        def state_writer(evidence: AffectEvidence) -> AffectState:
            folded.append(evidence)
            return _state(at=evidence.at)

        loop = EvidenceLoop(state_writer, observers)
        task = asyncio.create_task(loop.run())

        loop.submit(_evidence())
        await loop.drain()
        await _stop(task)

        assert len(folded) == 1
        assert [event.schema for event in seen] == ["evidence/1", "state/2"]

    asyncio.run(scenario())


def test_the_drain_returns_only_once_everything_submitted_has_been_folded():
    """Shutdown must lose nothing — the reason it drains instead of cancelling.

    Evidence still queued at the end of a session was generated by the participant, and
    dropping it leaves ``evidence.jsonl`` short of rows that ``utterances.jsonl`` says
    happened. That gap is invisible until the analysis, by which time the session cannot be
    repeated.

    Submitting before the consumer task starts is deliberate: producers are constructed and
    can submit before the scheduler has run the loop even once, so that path has to work.
    """
    async def scenario() -> None:
        folded: list[AffectEvidence] = []

        def state_writer(evidence: AffectEvidence) -> AffectState:
            folded.append(evidence)
            return _state(at=evidence.at)

        loop = EvidenceLoop(state_writer, Observers())
        for index in range(3):
            loop.submit(_evidence(source=f"test:{index}"))

        task = asyncio.create_task(loop.run())
        await loop.drain()
        await _stop(task)

        assert [evidence.source for evidence in folded] == ["test:0", "test:1", "test:2"]

    asyncio.run(scenario())


def test_a_failing_state_writer_stops_the_loop():
    """A broken affect model must end the session, not be absorbed like a broken observer.

    The two failures look alike and are not. An observer is outside the control path, so
    dropping its error costs data and nothing else. The state writer *is* the control path:
    swallow its error and the agent stops forming beliefs while continuing to render the
    last thing it felt — a robot that has quietly stopped responding, with no error anywhere
    and a recording that cannot be told apart from one where nothing happened.

    Note what this test would do if the error *were* swallowed: ``await task`` would never
    return, because the loop would go back to waiting for the next item.
    """
    async def scenario() -> None:
        def state_writer(evidence: AffectEvidence) -> AffectState:
            raise RuntimeError("model broken")

        loop = EvidenceLoop(state_writer, Observers())
        task = asyncio.create_task(loop.run())
        loop.submit(_evidence())

        with pytest.raises(RuntimeError, match="model broken"):
            await task

    asyncio.run(scenario())


def test_a_failed_fold_leaves_the_evidence_published_and_no_state():
    """Publishing before the fold is what makes the failure legible afterwards.

    Two things follow from the order, and both are lost if publishing moves after the fold.
    The evidence that killed the model is in the record rather than only in a traceback.
    And the failure gets a signature that needs no extra field: an evidence row with no
    state row after it is a fold that did not complete.

    Separate from the test above because they fail for different reasons — this one breaks
    if the publish moves, that one breaks if the raise is swallowed.
    """
    async def scenario() -> None:
        seen: list[Event] = []
        observers = Observers()
        observers.register(seen.append)

        def state_writer(evidence: AffectEvidence) -> AffectState:
            raise RuntimeError("model broken")

        loop = EvidenceLoop(state_writer, observers)
        task = asyncio.create_task(loop.run())
        loop.submit(_evidence())

        with pytest.raises(RuntimeError):
            await task

        assert [event.schema for event in seen] == ["evidence/1"]

    asyncio.run(scenario())


def test_a_failed_fold_still_marks_its_own_item_done():
    """``task_done`` in a ``finally``, tested because skipping it converts an error into a
    freeze.

    ``drain`` waits for one ``task_done`` per item *taken off* the queue. Without the
    ``finally`` the failing item is never marked, so the unfinished count never reaches zero
    and a drain waits forever — turning a fold bug into a hang, which is the symptom the
    fatal-error policy exists to remove. The timeout is the assertion: ``join`` either
    returns immediately here or never returns at all.

    **Scoped to the item in hand, which is all the ``finally`` can rescue.** Anything still
    queued behind it was never taken, so nothing will ever acknowledge it — a drain after a
    fatal failure hangs whenever a backlog existed. Exactly one item is submitted here for
    that reason, and it is why teardown must not drain on the fatal path: producers stop and
    the drain runs only when the session ends normally.
    """
    async def scenario() -> None:
        def state_writer(evidence: AffectEvidence) -> AffectState:
            raise RuntimeError("model broken")

        loop = EvidenceLoop(state_writer, Observers())
        task = asyncio.create_task(loop.run())
        loop.submit(_evidence())

        with pytest.raises(RuntimeError):
            await task

        await asyncio.wait_for(loop.drain(), timeout=1.0)

    asyncio.run(scenario())
